#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="b2evo%205.0.9-stable/b2evolution-5.0.9-stable-2014-05-15.zip"
URL="http://sourceforge.net/projects/evocms/files/b2evolution/$VERSION"

dl $URL /usr/local/src

