#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="6.11.5"
URL="https://github.com/b2evolution/b2evolution/archive/$VERSION.tar.gz"

dl $URL /usr/local/src

