#!/bin/sh -ex

DB_NAME=b2evolution
DB_USER=b2evolution
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/b2evolution

# unpack and set permissions
tar -xvf $SRC/5.2.2.tar.gz -C $SRC
mv $SRC/b2evolution-5.2.2/blogs $WEBROOT
rm -rf $SRC/b2evolution*
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/media
chown -R www-data:www-data $WEBROOT/skins/custom


# create configuration file
CONF=$WEBROOT/conf/_basic_config.php
cat >$CONF<<EOF
<?php
if( !defined('EVO_CONFIG_LOADED') ) die( 'Direct access is not supported.' );

\$maintenance_mode = 0;
\$allow_evodb_reset = 0;

\$db_config = array(
    'host' => 'localhost',
    'name' => '$DB_NAME',
    'user' => '$DB_USER',
    'password' => '$DB_PASS',
);
\$tableprefix = '';

\$baseurl = ( (isset(\$_SERVER['HTTPS']) && ( \$_SERVER['HTTPS'] != 'off' ) ) ?'https://':'http://').\$_SERVER['HTTP_HOST'].'/';

\$admin_email = '$ADMIN_MAIL'; // only used by installer
\$config_is_done = 1;
?>
EOF
chown www-data:www-data $CONF
chmod 640 $CONF

# configure apache
a2dissite 000-default
a2ensite b2evolution
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL="http://127.0.0.1/install/index.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}?locale=en-US&confirmed=0&installer_version=10&action=newdb&create_sample_contents=1"
$CURL "${URL}?locale=en-US&confirmed=0&installer_version=10&action=newdb&create_sample_contents=1&htignore=1"

rm -rf $WEBROOT/install
rm -f /tmp/cookie

# remove admin email from config (used only during installation)
CONF=$WEBROOT/conf/_basic_config.php
sed -i '/admin_email/d' $CONF

# set default password
MD5_PASS=$(echo -n $ADMIN_PASS | md5sum | cut -d " " -f 1)
$MYSQL_BATCH --execute "UPDATE $DB_NAME.users SET user_pass=\"$MD5_PASS\" WHERE user_login=\"$ADMIN_NAME\";"

# enable htaccess
mv $WEBROOT/sample.htaccess $WEBROOT/.htaccess

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

