#!/bin/bash -e
# regenerate b2evolution mysql password

. /etc/default/inithooks

CONF=/var/www/b2evolution/conf/_basic_config.php
PASSWORD=$(mcookie)
sed -i "s|password.*|password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=b2evolution --pass="$PASSWORD"

