#!/bin/bash -e
# set b2evolution admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/b2evolution.py --pass="$APP_PASS" --email="$APP_EMAIL"

